### ISSUE TITLE
téléphone

### ISSUE THREAD

**Issue by PatrickNeff** [DreamTeam3WA/idream#3]
j'ai rentré ppppppppppppppppppppp
il a rien trouvé à redire et à validé mon inscription

dans la modification, j'ai remplacé par rrrrrrrrrrrrrrrrrrr
il trouve rien à redire, mais m'affiche 0

**Comment by Shadownest** [comment]
J'ajoute aussi le fait que le numéro de téléphone qui commence par un 0, par exemple : 0123456789, n'affiche que 123456789 et pas le 0 de départ...
